name: Build

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Library Build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download dkp-pacman
      run: wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb

    - name: Install dkp-pacman
      run: sudo dpkg --install devkitpro-pacman.deb

    - name: Update packages from dkp-pacman to latest
      run: sudo dkp-pacman --sync --refresh --sysupgrade --noconfirm

    - name: Install packages required for build from dkp-pacman
      run: sudo dkp-pacman --sync --noconfirm devkitA64 devkit-env libnx switch-sdl2 switch-sdl2_gfx switch-sdl2_image switch-sdl2_ttf switch-freetype

    - name: Make library
      run: |
          source /etc/profile.d/devkit-env.sh
          export PATH=${PATH}:${DEVKITPRO}/portlibs/switch/bin
          make --directory=$GITHUB_WORKSPACE --file=$GITHUB_WORKSPACE/Makefile -j$(nproc) library